### ISSUE TITLE
grep -P in msg-matches-regex hook is not portable

### ISSUE THREAD

**Issue by jjlharrison** [rudikershaw/client-git-hooks#2]
`grep -P` is experimental in GNU grep (see https://linux.die.net/man/1/grep) and non-existent in BSD grep (see https://man.openbsd.org/grep).

This also means that the hook does not work on a Mac. Perhaps using `perl` directly would be better.

**Comment by rudikershaw** [comment]
It feels like adding a `perl` script would just add another language to worry about. Perhaps I am being too purist. 

I can probably switch to simply using `grep -E`, but I am having trouble trying to find out if the BSD `grep -E` supports `{}`. Would prefer to keep support for the `{}`.

**Comment by jjlharrison** [comment]
I meant using the `perl` command to evaluate the expression, not a separate script file.

**Comment by jjlharrison** [comment]
👍
