### ISSUE TITLE
Author name and email hook

### ISSUE THREAD

**Issue by rudikershaw** [rudikershaw/client-git-hooks#3]
Write a hook that insists that the author name and email address are set in the users config before committing.

**Comment by rudikershaw** [comment]
Done.

**Comment by jjlharrison** [comment]
You closed the wrong issue here? Looks like you’ve added the Docker build, not the author check.

**Comment by rudikershaw** [comment]
So I have, but I can remedy that without too much difficulty. Just need to push my changes.

**Comment by rudikershaw** [comment]
That should do it.
