### ISSUE TITLE
maximum-file-size hook doesn’t work on mac/BSD

### ISSUE THREAD

**Issue by jjlharrison** [rudikershaw/client-git-hooks#8]
The `-c` option doesn’t exist for the BSD variant of the `stat` command.

**Comment by rudikershaw** [comment]
I have added a macos build to Travis CI, so hopefully this won't happen again. Additionally I have fixed it (at least as far as Travis is concerned), and released a 2.0.1.

Can you check from your end when you get the chance, and close the issue if you're satisfied?

PS: Seeing orphaned commits on the issue history is a little annoying. Another reason not to re-write history I suppose.
